### ISSUE TITLE
No 'Access-Control-Allow-Origin' in ajax example.

### ISSUE THREAD

**Issue by philderbeast** [slamdata/purescript-halogen#335] opened 2016-11-05 19:43 UTC
When I hit the compile button of the ajax example I see the following error in chrome's console ...

> XMLHttpRequest cannot load http://try.purescript.org/compile/text. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 403.

**Comment by garyb** [comment] 2016-11-06 13:12
Thanks, but closing as this is a duplicate of #139.

**Closed by garyb** 2016-11-06 13:12 UTC
Labels: duplicate
