### ISSUE TITLE
Remove initializers and finalizers?

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#110] opened 2015-05-05 04:01 UTC
Post-render hooks allow us to attach initializers and finalizers.

**Comment by jdegoes** [comment] 2015-05-06 00:45
The problem is that it pushes a declarative solution into an imperative one best done by jQuery. Maybe that's what 0.5 wants to be and maybe that's what we have to do in this release, but I mentioned it to @puffnfresh and he did not like the idea of removing these -- let's chat more tomorrow when he's in the office (and get @garyb and @cryogenian's feedback, too).

**Comment by jdegoes** [comment] 2015-06-30 13:50
I do think we need a better solution here, I'm not sure exactly what that looks like but it will be influenced by whatever comes out of #138. Post-render hook is a *global imperative* solution, what I'd really prefer is a *local declarative* solution.

**Closed by jdegoes** 2015-06-30 13:50 UTC
Labels: question

**Comment by garyb** [comment] 2015-06-30 13:52
I'm not necessarily sure there is a better solution than post-render hooks, as for the kind of initialization we use these for we need an element in the DOM to actually exist.

**Comment by jdegoes** [comment] 2015-06-30 13:54
Well, what if `Initializer i` was changed to `Initializer (HTMLElement -> i)`, for example? The library can take care to call it after the element in the DOM actually exists.
