### ISSUE TITLE
support for purescript 0.7

### ISSUE THREAD

**Issue by timbod7** [slamdata/purescript-halogen#145] opened 2015-07-14 08:54 UTC
It looks like there hasn't been a release to support purescript 0.7 yet. Bower doesn't seem to install master successfully:

```
18:53:25 /tmp/tests$ bower install purescript-halogen#master
bower purescript-halogen#master       not-cached git://github.com/slamdata/purescript-halogen.git#master
bower purescript-halogen#master          resolve git://github.com/slamdata/purescript-halogen.git#master
bower purescript-halogen#master         checkout master
bower purescript-halogen#master     invalid-meta purescript-halogen is missing "main" entry in bower.json
bower purescript-halogen#master         resolved git://github.com/slamdata/purescript-halogen.git#0ed8df5900
bower purescript-void#0.7-update      not-cached git://github.com/garyb/purescript-void.git#0.7-update
bower purescript-void#0.7-update         resolve git://github.com/garyb/purescript-void.git#0.7-update
bower purescript-css#^0.2.0               cached git://github.com/slamdata/purescript-css.git#0.2.0
bower purescript-css#^0.2.0             validate 0.2.0 against git://github.com/slamdata/purescript-css.git#^0.2.0
bower purescript-aff#^0.11.0              cached git://github.com/slamdata/purescript-aff.git#0.11.0
bower purescript-aff#^0.11.0            validate 0.11.0 against git://github.com/slamdata/purescript-aff.git#^0.11.0
bower purescript-exists#^0.2.0            cached git://github.com/paf31/purescript-exists.git#0.2.0
bower purescript-exists#^0.2.0          validate 0.2.0 against git://github.com/paf31/purescript-exists.git#^0.2.0
bower purescript-foreign#^0.5.0           cached git://github.com/purescript/purescript-foreign.git#0.5.0
bower purescript-foreign#^0.5.0         validate 0.5.0 against git://github.com/purescript/purescript-foreign.git#^0.5.0
bower purescript-nullable#^0.2.0          cached git://github.com/paf31/purescript-nullable.git#0.2.0
bower purescript-nullable#^0.2.0        validate 0.2.0 against git://github.com/paf31/purescript-nullable.git#^0.2.0
bower purescript-profunctor#^0.3.0        cached git://github.com/mankyKitty/purescript-profunctor.git#0.3.0
bower purescript-profunctor#^0.3.0      validate 0.3.0 against git://github.com/mankyKitty/purescript-profunctor.git#^0.3.0
bower purescript-simple-dom#6358414013eb3106d695e3e19488609f82d903e9           cached git://github.com/aktowns/purescript-simple-dom.git#6358414013
bower purescript-simple-dom#6358414013eb3106d695e3e19488609f82d903e9         validate 6358414013 against git://github.com/aktowns/purescript-simple-dom.git#6358414013eb3106d695e3e19488609f82d903e9
bower purescript-refs#^0.2.0                                                   cached git://github.com/purescript/purescript-refs.git#0.2.0
bower purescript-refs#^0.2.0                                                 validate 0.2.0 against git://github.com/purescript/purescript-refs.git#^0.2.0
bower purescript-unsafe-coerce#^0.1.0                                          cached git://github.com/purescript-contrib/purescript-unsafe-coerce.git#0.1.0
bower purescript-unsafe-coerce#^0.1.0                                        validate 0.1.0 against git://github.com/purescript-contrib/purescript-unsafe-coerce.git#^0.1.0
bower purescript-dom#^0.1.0                                                    cached git://github.com/joneshf/purescript-dom.git#0.1.2
bower purescript-dom#^0.1.0                                                  validate 0.1.2 against git://github.com/joneshf/purescript-dom.git#^0.1.0
bower purescript-arrays#^0.4.0                                                 cached git://github.com/purescript/purescript-arrays.git#0.4.0
bower purescript-arrays#^0.4.0                                               validate 0.4.0 against git://github.com/purescript/purescript-arrays.git#^0.4.0
bower purescript-maybe#^0.3.0                                                  cached git://github.com/purescript/purescript-maybe.git#0.3.2
bower purescript-maybe#^0.3.0                                                validate 0.3.2 against git://github.com/purescript/purescript-maybe.git#^0.3.0
bower purescript-foldable-traversable#^0.4.0                                   cached git://github.com/purescript/purescript-foldable-traversable.git#0.4.0
bower purescript-foldable-traversable#^0.4.0                                 validate 0.4.0 against git://github.com/purescript/purescript-foldable-traversable.git#^0.4.0
bower purescript-tuples#^0.4.0                                                 cached git://github.com/purescript/purescript-tuples.git#0.4.0
bower purescript-tuples#^0.4.0                                               validate 0.4.0 against git://github.com/purescript/purescript-tuples.git#^0.4.0
bower purescript-strings#^0.5.0                                                cached git://github.com/purescript/purescript-strings.git#0.5.3
bower purescript-strings#^0.5.0                                              validate 0.5.3 against git://github.com/purescript/purescript-strings.git#^0.5.0
bower purescript-sets#^0.4.0                                                   cached git://github.com/purescript/purescript-sets.git#0.4.0
bower purescript-sets#^0.4.0                                                 validate 0.4.0 against git://github.com/purescript/purescript-sets.git#^0.4.0
bower purescript-void#0.7-update                                             checkout 0.7-update
bower purescript-nonempty-arrays#0.7-updates                               not-cached git://github.com/garyb/purescript-nonempty-array.git#0.7-updates
bower purescript-nonempty-arrays#0.7-updates                                  resolve git://github.com/garyb/purescript-nonempty-array.git#0.7-updates
bower purescript-prelude#~0.1.0                                                cached git://github.com/purescript/purescript-prelude.git#0.1.0
bower purescript-prelude#~0.1.0                                              validate 0.1.0 against git://github.com/purescript/purescript-prelude.git#~0.1.0
bower purescript-console#~0.1.0                                                cached git://github.com/purescript/purescript-console.git#0.1.0
bower purescript-console#~0.1.0                                              validate 0.1.0 against git://github.com/purescript/purescript-console.git#~0.1.0
bower purescript-either#~0.2.0                                                 cached git://github.com/purescript/purescript-either.git#0.2.0
bower purescript-either#~0.2.0                                               validate 0.2.0 against git://github.com/purescript/purescript-either.git#~0.2.0
bower purescript-monoid#~0.3.0                                                 cached git://github.com/purescript/purescript-monoid.git#0.3.0
bower purescript-monoid#~0.3.0                                               validate 0.3.0 against git://github.com/purescript/purescript-monoid.git#~0.3.0
bower purescript-exceptions#~0.3.0                                             cached git://github.com/purescript/purescript-exceptions.git#0.3.0
bower purescript-exceptions#~0.3.0                                           validate 0.3.0 against git://github.com/purescript/purescript-exceptions.git#~0.3.0
bower purescript-eff#~0.1.0                                                    cached git://github.com/purescript/purescript-eff.git#0.1.0
bower purescript-eff#~0.1.0                                                  validate 0.1.0 against git://github.com/purescript/purescript-eff.git#~0.1.0
bower purescript-control#~0.3.0                                                cached git://github.com/purescript/purescript-control.git#0.3.0
bower purescript-control#~0.3.0                                              validate 0.3.0 against git://github.com/purescript/purescript-control.git#~0.3.0
bower purescript-transformers#~0.6.0                                           cached git://github.com/purescript/purescript-transformers.git#0.6.1
bower purescript-transformers#~0.6.0                                         validate 0.6.1 against git://github.com/purescript/purescript-transformers.git#~0.6.0
bower purescript-functions#~0.1.0                                              cached git://github.com/purescript/purescript-functions.git#0.1.0
bower purescript-functions#~0.1.0                                            validate 0.1.0 against git://github.com/purescript/purescript-functions.git#~0.1.0
bower purescript-these#^0.3.0                                                  cached git://github.com/purescript-contrib/purescript-these.git#0.3.0
bower purescript-these#^0.3.0                                                validate 0.3.0 against git://github.com/purescript-contrib/purescript-these.git#^0.3.0
bower purescript-integers#^0.2.0                                               cached git://github.com/purescript/purescript-integers.git#0.2.0
bower purescript-integers#^0.2.0                                             validate 0.2.0 against git://github.com/purescript/purescript-integers.git#^0.2.0
bower purescript-bifunctors#^0.4.0                                             cached git://github.com/purescript-contrib/purescript-bifunctors.git#0.4.0
bower purescript-bifunctors#^0.4.0                                           validate 0.4.0 against git://github.com/purescript-contrib/purescript-bifunctors.git#^0.4.0
bower purescript-st#^0.1.0                                                     cached git://github.com/purescript/purescript-st.git#0.1.0
bower purescript-st#^0.1.0                                                   validate 0.1.0 against git://github.com/purescript/purescript-st.git#^0.1.0
bower purescript-maps#^0.4.0                                                   cached git://github.com/purescript/purescript-maps.git#0.4.0
bower purescript-maps#^0.4.0                                                 validate 0.4.0 against git://github.com/purescript/purescript-maps.git#^0.4.0
bower purescript-void#0.7-update                                         invalid-meta purescript-void is missing "main" entry in bower.json
bower purescript-void#0.7-update                                         invalid-meta purescript-void is missing "ignore" entry in bower.json
bower purescript-void#0.7-update                                             resolved git://github.com/garyb/purescript-void.git#979e3e721c
bower purescript-nonempty-arrays#0.7-updates                             ENORESTARGET Tag/branch 0.7-updates does not exist

Additional error details:
Available tags: 0.0.2, 0.0.3, 0.1.0, 0.2.0, 1.3
Available branches: master
18:53:45 /tmp/tests$ 
```

Am I just trying this too soon?

**Comment by garyb** [comment] 2015-07-14 09:08
This error is caused by a problem with `purescript-css`'s dependencies actually. I've just bumped the version in `master`'s `bower.json` so it should be installable now.

I've not made a release yet as Halogen currently has other unreleased dependencies too, so would prefer those to be tagged rather than using explicit hash/branch dependencies before doing so (that was actually the problem with `purescript-css` - released too early).

**Comment by timbod7** [comment] 2015-07-14 09:18
Thanks heaps - that has solved my problem for now.

Is there any way in bower to override the versions loaded for transitive dependencies?

**Comment by garyb** [comment] 2015-07-14 09:20
You can manually install a "correct" version of a dependency first, and then when bower complains of a conflict you can choose the version you want (and force it to be saved using the "resolutions" mechanism if you like too). A bit hacky though. :wink:

**Comment by timbod7** [comment] 2015-07-14 09:21
Ok.

I'm good for now - should I leave this issue open until there is an official release?

**Comment by garyb** [comment] 2015-07-14 09:28
Yes please, I'll close it when the release is made, and then you can add the specific version dependency to your project also.

**Comment by BartAdv** [comment] 2015-08-14 22:30
Hello,

What would be the way to install halogen now (with psc 0.7.2.0)? When installing latest release it doesn't build due to `purescript-strings` version (0.4.5) using inline foreign literals.

**Comment by garyb** [comment] 2015-08-14 22:45
If you install using the version hash `0ed8df5900e0eef8cdb9de5bf7039ab93c196903` that will let you use "old halogen" with 0.7.2, but the 0.5 release is nearly done now - it changes the architecture rather a lot as well as being updated for 0.7+. 

I'm about to open a PR which will remove conflicts from the master branch, so that would work too if you want to use "new halogen" instead.

**Comment by garyb** [comment] 2015-08-14 22:48
Actually, that PR won't be right now, I need to update some of the example dependencies first :)

**Comment by BartAdv** [comment] 2015-08-14 22:49
Thanks, I'd most likely want to go with the new thing, as I just wanted to
evaluate both purescript and halogen.

On 15 Aug 2015 00:45, "Gary Burgess" <notifications@github.com> wrote:
>
> If you install using the version hash
0ed8df5900e0eef8cdb9de5bf7039ab93c196903 that will let you use "old
halogen" with 0.7.2, but the 0.5 release is nearly done now - it changes
the architecture rather a lot as well as being updated for 0.7+.
>
> I'm about to open a PR which will remove conflicts from the master
branch, so that would work too if you want to use "new halogen" instead.

**Comment by garyb** [comment] 2015-08-14 22:55
@BartAdv you can try this out for now: https://github.com/garyb/purescript-halogen/tree/wip/dom

The Ace example and the Ajax example need their dependencies updating, but probably the best showcase of how an app might work now anyway is the Todo example.

**Comment by BartAdv** [comment] 2015-08-15 08:44
Thanks, builds fine.

**Comment by garyb** [comment] 2015-10-16 18:18
We finally have a release (!), so closing this now.

**Closed by garyb** 2015-10-16 18:18 UTC
