### ISSUE TITLE
Support thunks

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#109] opened 2015-05-03 19:40 UTC
I'm not sure exactly what this would look like, but there are cases where entire subtrees only depend on a few parameters, and we can eliminate the diff entirely if we can establish that those parameters did not change. 

This could use `Eq`, or we could even try to restrict the parameters to those types where we can use `===` as an equality test.

`virtual-dom` provides `Thunk` for these sorts of things.

**Comment by ul** [comment] 2015-12-18 18:24
And further improvement could be made by wrapping every component (or by user choice) not in Thunks, but in [Widgets](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/widget.md). Just allow component to have its own virtual tree and render cycle, and mount it as Widget to parent. I don't know if this idea is compatible with Halogen architecture, but it will eliminate touching parent components up to the root on child state change. Keeping all other benefits of virtual tree safe: widgets are first-class citizens of diff/patch cycle, including ability to provide key for reordering.

**Comment by natefaubion** [comment] 2015-12-18 18:50
@ul I think this would be really neat, but I'm not sure the `virtual-dom` notion of a widget is quite compatible since it relies on referential identity to determine the patch (though I'd be happy to be proven wrong).

As review, a `Widget` is an object that has a `type` property set to "Widget" with `init`, `update`, and `destroy` methods. Additionally you can give it a `name` and `id`. If it has a name, then the ids are compared using `===`. If we wanted to wrap all components in a `Widget` then we'd either have to have the user specify the `id` in their Component definition using some sort of globally unique string, or use the actual `Component` newtype as the `id`. I don't think this is quite right. It would be nice if virtual-dom provided actual hooks for determining equality.

**Comment by ul** [comment] 2015-12-18 20:19
`Widget` is the way to provide full control over patching to the user, and it relies only on his decision. Actually, `virtual-dom` only adds or removes widget if object with type `Widget` appear or disappear in that particular place of virtual tree. `virtual-dom` does not care if it is the same widget or not on diffing tree, it just calls `update` on the current widget, passing previous widget and node to it as arguments, and expects a new real node or `null` to be returned (the latter signals that no need to replace widget's root node, though widget itself is free to patch its subtree).

Thus wrapper can close over component function and arguments on creation, create virtual tree and return real node on `init`, and on `update` consider three options:
* component function and arguments are the same — just return `null`
* component function is the same, but arguments changed — return `null` and do diff & patch
* everything has changed — mount new component

Actually, depending on implementation, 2nd and 3rd options could collapse into one.

The problem is that functions (which are components) does not implement `Eq` typeclass in Purescript. But functions _are_ comparable in Javascript, so we can take advantage of underlying platform (as far as all story with using `virtual-dom` and doing optimizations like `Widget` is about deep interaction with platform I don't think that it will be a horrible hack). May be even better to implement wrapper widget entirely in Javascript.

**Comment by natefaubion** [comment] 2015-12-18 20:59
I think instead of checking arguments using referential equality, you'd want to give it a function that can compare the slots of a component (all slots implement `Eq`). Since everything is wrapped in the same generic widget, you need to distinguish between two different widgets to properly handle lifecycles, wouldn't you?

**Comment by natefaubion** [comment] 2015-12-18 21:13
I'm just very suspicious of tying meaning to a function's referential equality, because it always breaks things in subtle ways. For example, right now you can parameterize a component so your "component" is really a function to a component. On a referential level, this is stamping out unique components each time, regardless of what arguments you pass in to instantiate it, but right now, this is irrelevant. It doesn't matter if your component is static, if its a function, or if you define it inline (substitution).

**Comment by ul** [comment] 2015-12-18 21:15
Yes, that's the main problem: we need robust way to compare and distinguish components.

**Comment by natefaubion** [comment] 2016-03-11 15:18
FYI, the upcoming 0.6 uses widgets to handle thunking. Identity is given to a component via its slot, and thunking is done based on whether the state for the component was changed. We still don't have local updates, but it should be possible in theory.

**Comment by garyb** [comment] 2016-03-11 15:20
Thanks for the comment, I missed this one. I'll close this as it's pretty much in place now (#280 again).

**Closed by garyb** 2016-03-11 15:20 UTC
Labels: enhancement, idea
